spring:
  datasource:
    url: jdbc:postgresql://192.168.0.5:5432/business_profile
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

resilience4j:
  retry:
    instances:
      profileValidation:
        maxRetryAttempts: 3
        waitDuration: 1s
        retryExceptions: org.springframework.web.client.HttpStatusCodeException

