CREATE TABLE T_PROFILE(
    ID VARCHAR(36) NOT NULL,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    COMPANY_LEGAL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    WEBSITE VARCHAR(255) NOT NULL,
    CONSTRAINT "PK_T_PROFILE" PRIMARY KEY (ID)
);

CREATE TABLE T_ADDRESS(
    ID VARCHAR(36) NOT NULL,
    LINE_1 VARCHAR(255) NOT NULL,
    LINE_2 VARCHAR(255),
    CITY VARCHAR(32) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    ZIP VARCHAR(16) NOT NULL,
    COUNTRY VARCHAR(32) NOT NULL,
    ADDRESS_TYPE VARCHAR(16) NOT NULL,
    PROFILE_ID VARCHAR(36) NOT NULL,
    CONSTRAINT "PK_T_ADDRESS" PRIMARY KEY (ID),
    CONSTRAINT "ADDRESS_PROFILEID_FK" FOREIGN KEY (PROFILE_ID) REFERENCES T_PROFILE(ID)
            ON UPDATE RESTRICT
            ON DELETE CASCADE
);

CREATE TABLE T_PRODUCT_SUBSCRIPTION(
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_ID VARCHAR(10) NOT NULL,
    PROFILE_ID VARCHAR(36) NOT NULL,
    CONSTRAINT "PK_T_PRODUCT_SUBSCRIPTION" PRIMARY KEY (PRODUCT_ID, PROFILE_ID),
    CONSTRAINT "SUBSCRIPTION_PROFILEID_FK" FOREIGN KEY (PROFILE_ID) REFERENCES T_PROFILE(ID)
                ON UPDATE RESTRICT
                ON DELETE CASCADE
);

CREATE TABLE T_TAX_IDENTIFIER(
    ID VARCHAR(36) NOT NULL,
    PAN VARCHAR(16) NOT NULL,
    EIN VARCHAR(16) NOT NULL,
    PROFILE_ID VARCHAR(36) NOT NULL,
    CONSTRAINT "PK_T_TAX_IDENTIFIER" PRIMARY KEY (ID),
    CONSTRAINT "TAX_IDENTIFIER_PROFILEID_FK" FOREIGN KEY (PROFILE_ID) REFERENCES T_PROFILE(ID)
                ON UPDATE RESTRICT
                ON DELETE CASCADE
);

CREATE TABLE T_JOB(
    ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CORRELATION_ID VARCHAR(36) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    PAYLOAD TEXT NOT NULL,
    ERROR VARCHAR(255),
    PROFILE_ID VARCHAR(36),
    CONSTRAINT "PK_T_JOB" PRIMARY KEY (ID)
);

